# Generated by Django 4.2.7 on 2023-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adv",
            fields=[
                ("sneaker_id", models.CharField(max_length=255)),
                (
                    "adv_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("adv_name", models.CharField(max_length=255)),
                ("adv_num", models.IntegerField()),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "advantage",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "bolg_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("blog_title", models.CharField(max_length=255)),
                ("blog_content", models.CharField(max_length=255)),
                ("blog_img", models.CharField(max_length=255)),
                ("blog_time", models.DateTimeField()),
                ("blog_liked", models.IntegerField()),
                ("blog_comment_num", models.IntegerField()),
                ("blog_visited", models.IntegerField()),
                ("blog_label", models.CharField(max_length=255)),
                ("blog_categroy", models.CharField(max_length=255)),
                ("blog_recommand", models.IntegerField()),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "blog",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "brand_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("brand_img", models.CharField(max_length=255)),
                ("brand_name", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "brand",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("blog_id", models.CharField(max_length=255)),
                ("sneaker_id", models.CharField(max_length=255)),
                (
                    "comment_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("comment_time", models.CharField(max_length=255)),
                ("comment_content", models.CharField(max_length=255)),
                ("father_id", models.CharField(max_length=255)),
                ("user_rating", models.FloatField()),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="Disadv",
            fields=[
                ("sneaker_id", models.CharField(max_length=255)),
                (
                    "disadv_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("disadv_name", models.CharField(max_length=255)),
                ("disadv_num", models.IntegerField()),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "disadvantage",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("follower", models.CharField(max_length=255)),
                ("followed", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "follow",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "like_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("blog_id", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "like",
            },
        ),
        migrations.CreateModel(
            name="Sneaker",
            fields=[
                (
                    "sneaker_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("sneaker_brand", models.CharField(max_length=255)),
                ("sneaker_model", models.CharField(max_length=255)),
                ("sneaker_rating", models.FloatField()),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "sneaker",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_psd", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_info", models.CharField(max_length=255)),
                ("user_like", models.IntegerField()),
                ("user_fans", models.IntegerField()),
                ("user_follow", models.IntegerField()),
                ("user_img", models.CharField(max_length=255)),
                ("user_ip", models.CharField(max_length=255)),
                ("user_blog_num", models.IntegerField()),
                ("user_emial", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField()),
                ("updatedAt", models.DateTimeField()),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
