# Generated by Django 4.2.7 on 2023-12-07 10:09

import cbo.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cbo", "0002_alter_blog_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="blog",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", cbo.models.UserManager()),
            ],
        ),
    ]
